type CurrencyEntry = {
  code: string;
  symbol: string;
  name: string;
};

const COMMON_SYMBOLS: Record<string, string> = {
  AED: 'د.إ',
  AFN: '؋',
  ALL: 'L',
  AMD: '֏',
  ANG: 'ƒ',
  AOA: 'Kz',
  ARS: '$',
  AUD: 'A$',
  AWG: 'ƒ',
  AZN: '₼',
  BAM: 'KM',
  BBD: '$',
  BDT: '৳',
  BGN: 'лв',
  BHD: '.د.ب',
  BIF: 'FBu',
  BMD: '$',
  BND: '$',
  BOB: 'Bs',
  BRL: 'R$',
  BSD: '$',
  BTN: 'Nu.',
  BWP: 'P',
  BYN: 'Br',
  BZD: '$',
  CAD: 'C$',
  CDF: 'FC',
  CHF: 'CHF',
  CLP: '$',
  CNY: '¥',
  COP: '$',
  CRC: '₡',
  CUP: '$',
  CVE: '$',
  CZK: 'Kč',
  DJF: 'Fdj',
  DKK: 'kr',
  DOP: 'RD$',
  DZD: 'د.ج',
  EGP: 'E£',
  ERN: 'Nfk',
  ETB: 'Br',
  EUR: '€',
  FJD: '$',
  FKP: '£',
  GBP: '£',
  GEL: '₾',
  GGP: '£',
  GHS: '₵',
  GIP: '£',
  GMD: 'D',
  GNF: 'FG',
  GTQ: 'Q',
  GYD: '$',
  HKD: 'HK$',
  HNL: 'L',
  HTG: 'G',
  HUF: 'Ft',
  IDR: 'Rp',
  ILS: '₪',
  IMP: '£',
  INR: '₹',
  IQD: 'ع.د',
  IRR: '﷼',
  ISK: 'kr',
  JEP: '£',
  JMD: 'J$',
  JOD: 'JD',
  JPY: '¥',
  KES: 'KSh',
  KGS: 'сом',
  KHR: '៛',
  KMF: 'CF',
  KPW: '₩',
  KRW: '₩',
  KWD: 'KD',
  KYD: '$',
  KZT: '₸',
  LAK: '₭',
  LBP: 'ل.ل',
  LKR: 'Rs',
  LRD: '$',
  LSL: 'L',
  LYD: 'LD',
  MAD: 'د.م.',
  MDL: 'L',
  MGA: 'Ar',
  MKD: 'ден',
  MMK: 'K',
  MNT: '₮',
  MOP: 'MOP$',
  MRU: 'UM',
  MUR: '₨',
  MVR: 'Rf',
  MWK: 'MK',
  MXN: '$',
  MYR: 'RM',
  MZN: 'MT',
  NAD: '$',
  NGN: '₦',
  NIO: 'C$',
  NOK: 'kr',
  NPR: 'Rs',
  NZD: 'NZ$',
  OMR: '﷼',
  PAB: 'B/.',
  PEN: 'S/',
  PGK: 'K',
  PHP: '₱',
  PKR: '₨',
  PLN: 'zł',
  PYG: '₲',
  QAR: 'ر.ق',
  RON: 'lei',
  RSD: 'дин.',
  RUB: '₽',
  RWF: 'FRw',
  SAR: '﷼',
  SBD: '$',
  SCR: '₨',
  SDG: 'ج.س.',
  SEK: 'kr',
  SGD: 'S$',
  SHP: '£',
  SLE: 'Le',
  SLL: 'Le',
  SOS: 'Sh',
  SRD: '$',
  SSP: '£',
  STN: 'Db',
  SVC: '$',
  SYP: '£',
  SZL: 'L',
  THB: '฿',
  TJS: 'ЅМ',
  TMT: 'm',
  TND: 'د.ت',
  TOP: 'T$',
  TRY: '₺',
  TTD: 'TT$',
  TWD: 'NT$',
  TZS: 'Sh',
  UAH: '₴',
  UGX: 'USh',
  USD: '$',
  UYU: '$U',
  UZS: "so'm",
  VES: 'Bs.',
  VND: '₫',
  VUV: 'VT',
  WST: 'WS$',
  XAF: 'FCFA',
  XCD: '$',
  XOF: 'CFA',
  XPF: '₣',
  YER: '﷼',
  ZAR: 'R',
  ZMW: 'ZK',
  ZWL: '$',
};

const CURRENCY_DATA = [
  ['AED', 'United Arab Emirates Dirham'],
  ['AFN', 'Afghan Afghani'],
  ['ALL', 'Albanian Lek'],
  ['AMD', 'Armenian Dram'],
  ['ANG', 'Netherlands Antillean Guilder'],
  ['AOA', 'Angolan Kwanza'],
  ['ARS', 'Argentine Peso'],
  ['AUD', 'Australian Dollar'],
  ['AWG', 'Aruban Florin'],
  ['AZN', 'Azerbaijani Manat'],
  ['BAM', 'Bosnia and Herzegovina Convertible Mark'],
  ['BBD', 'Barbadian Dollar'],
  ['BDT', 'Bangladeshi Taka'],
  ['BGN', 'Bulgarian Lev'],
  ['BHD', 'Bahraini Dinar'],
  ['BIF', 'Burundian Franc'],
  ['BMD', 'Bermudian Dollar'],
  ['BND', 'Brunei Dollar'],
  ['BOB', 'Bolivian Boliviano'],
  ['BRL', 'Brazilian Real'],
  ['BSD', 'Bahamian Dollar'],
  ['BTN', 'Bhutanese Ngultrum'],
  ['BWP', 'Botswana Pula'],
  ['BYN', 'Belarusian Ruble'],
  ['BZD', 'Belize Dollar'],
  ['CAD', 'Canadian Dollar'],
  ['CDF', 'Congolese Franc'],
  ['CHF', 'Swiss Franc'],
  ['CLP', 'Chilean Peso'],
  ['CNY', 'Chinese Yuan'],
  ['COP', 'Colombian Peso'],
  ['CRC', 'Costa Rican Colon'],
  ['CUP', 'Cuban Peso'],
  ['CVE', 'Cape Verdean Escudo'],
  ['CZK', 'Czech Koruna'],
  ['DJF', 'Djiboutian Franc'],
  ['DKK', 'Danish Krone'],
  ['DOP', 'Dominican Peso'],
  ['DZD', 'Algerian Dinar'],
  ['EGP', 'Egyptian Pound'],
  ['ERN', 'Eritrean Nakfa'],
  ['ETB', 'Ethiopian Birr'],
  ['EUR', 'Euro'],
  ['FJD', 'Fijian Dollar'],
  ['FKP', 'Falkland Islands Pound'],
  ['GBP', 'British Pound Sterling'],
  ['GEL', 'Georgian Lari'],
  ['GGP', 'Guernsey Pound'],
  ['GHS', 'Ghanaian Cedi'],
  ['GIP', 'Gibraltar Pound'],
  ['GMD', 'Gambian Dalasi'],
  ['GNF', 'Guinean Franc'],
  ['GTQ', 'Guatemalan Quetzal'],
  ['GYD', 'Guyanese Dollar'],
  ['HKD', 'Hong Kong Dollar'],
  ['HNL', 'Honduran Lempira'],
  ['HTG', 'Haitian Gourde'],
  ['HUF', 'Hungarian Forint'],
  ['IDR', 'Indonesian Rupiah'],
  ['ILS', 'Israeli New Shekel'],
  ['IMP', 'Isle of Man Pound'],
  ['INR', 'Indian Rupee'],
  ['IQD', 'Iraqi Dinar'],
  ['IRR', 'Iranian Rial'],
  ['ISK', 'Icelandic Krona'],
  ['JEP', 'Jersey Pound'],
  ['JMD', 'Jamaican Dollar'],
  ['JOD', 'Jordanian Dinar'],
  ['JPY', 'Japanese Yen'],
  ['KES', 'Kenyan Shilling'],
  ['KGS', 'Kyrgyzstani Som'],
  ['KHR', 'Cambodian Riel'],
  ['KMF', 'Comorian Franc'],
  ['KPW', 'North Korean Won'],
  ['KRW', 'South Korean Won'],
  ['KWD', 'Kuwaiti Dinar'],
  ['KYD', 'Cayman Islands Dollar'],
  ['KZT', 'Kazakhstani Tenge'],
  ['LAK', 'Lao Kip'],
  ['LBP', 'Lebanese Pound'],
  ['LKR', 'Sri Lankan Rupee'],
  ['LRD', 'Liberian Dollar'],
  ['LSL', 'Lesotho Loti'],
  ['LYD', 'Libyan Dinar'],
  ['MAD', 'Moroccan Dirham'],
  ['MDL', 'Moldovan Leu'],
  ['MGA', 'Malagasy Ariary'],
  ['MKD', 'Macedonian Denar'],
  ['MMK', 'Myanmar Kyat'],
  ['MNT', 'Mongolian Tugrik'],
  ['MOP', 'Macanese Pataca'],
  ['MRU', 'Mauritanian Ouguiya'],
  ['MUR', 'Mauritian Rupee'],
  ['MVR', 'Maldivian Rufiyaa'],
  ['MWK', 'Malawian Kwacha'],
  ['MXN', 'Mexican Peso'],
  ['MYR', 'Malaysian Ringgit'],
  ['MZN', 'Mozambican Metical'],
  ['NAD', 'Namibian Dollar'],
  ['NGN', 'Nigerian Naira'],
  ['NIO', 'Nicaraguan Cordoba'],
  ['NOK', 'Norwegian Krone'],
  ['NPR', 'Nepalese Rupee'],
  ['NZD', 'New Zealand Dollar'],
  ['OMR', 'Omani Rial'],
  ['PAB', 'Panamanian Balboa'],
  ['PEN', 'Peruvian Sol'],
  ['PGK', 'Papua New Guinean Kina'],
  ['PHP', 'Philippine Peso'],
  ['PKR', 'Pakistani Rupee'],
  ['PLN', 'Polish Zloty'],
  ['PYG', 'Paraguayan Guarani'],
  ['QAR', 'Qatari Riyal'],
  ['RON', 'Romanian Leu'],
  ['RSD', 'Serbian Dinar'],
  ['RUB', 'Russian Ruble'],
  ['RWF', 'Rwandan Franc'],
  ['SAR', 'Saudi Riyal'],
  ['SBD', 'Solomon Islands Dollar'],
  ['SCR', 'Seychellois Rupee'],
  ['SDG', 'Sudanese Pound'],
  ['SEK', 'Swedish Krona'],
  ['SGD', 'Singapore Dollar'],
  ['SHP', 'Saint Helena Pound'],
  ['SLE', 'Sierra Leonean Leone'],
  ['SLL', 'Sierra Leonean Leone'],
  ['SOS', 'Somali Shilling'],
  ['SRD', 'Surinamese Dollar'],
  ['SSP', 'South Sudanese Pound'],
  ['STN', 'Sao Tome and Principe Dobra'],
  ['SVC', 'Salvadoran Colon'],
  ['SYP', 'Syrian Pound'],
  ['SZL', 'Eswatini Lilangeni'],
  ['THB', 'Thai Baht'],
  ['TJS', 'Tajikistani Somoni'],
  ['TMT', 'Turkmenistani Manat'],
  ['TND', 'Tunisian Dinar'],
  ['TOP', "Tongan Pa'anga"],
  ['TRY', 'Turkish Lira'],
  ['TTD', 'Trinidad and Tobago Dollar'],
  ['TWD', 'New Taiwan Dollar'],
  ['TZS', 'Tanzanian Shilling'],
  ['UAH', 'Ukrainian Hryvnia'],
  ['UGX', 'Ugandan Shilling'],
  ['USD', 'US Dollar'],
  ['UYU', 'Uruguayan Peso'],
  ['UZS', 'Uzbekistani Som'],
  ['VES', 'Venezuelan Bolivar'],
  ['VND', 'Vietnamese Dong'],
  ['VUV', 'Vanuatu Vatu'],
  ['WST', 'Samoan Tala'],
  ['XAF', 'Central African CFA Franc'],
  ['XCD', 'East Caribbean Dollar'],
  ['XOF', 'West African CFA Franc'],
  ['XPF', 'CFP Franc'],
  ['YER', 'Yemeni Rial'],
  ['ZAR', 'South African Rand'],
  ['ZMW', 'Zambian Kwacha'],
  ['ZWL', 'Zimbabwean Dollar'],
] as const;

const getIntlSymbol = (code: string) => {
  try {
    const parts = new Intl.NumberFormat('en', {
      style: 'currency',
      currency: code,
      currencyDisplay: 'narrowSymbol',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).formatToParts(0);
    return parts.find((part) => part.type === 'currency')?.value;
  } catch {
    return undefined;
  }
};

export const CURRENCIES: CurrencyEntry[] = CURRENCY_DATA.map(([code, name]) => ({
  code,
  name,
  symbol: COMMON_SYMBOLS[code] || getIntlSymbol(code) || code,
}));

const CURRENCY_MAP = Object.fromEntries(CURRENCIES.map((entry) => [entry.code, entry])) as Record<string, CurrencyEntry>;

export const getCurrencySymbol = (code = 'USD') => {
  const key = String(code).toUpperCase();
  return CURRENCY_MAP[key]?.symbol || getIntlSymbol(key) || '$';
};

export default CURRENCIES;
